workspace: true

stages:
  - build
  - test
  - deploy

jobs:
- name: build:prepare
  stage: build
  image: sujoydatta/ac_docker_image:stable
  environment:
    TWO_FACTOR_KEY: 03238c9f03a392470c1608d0961b7941d455864995f7373ba4bb378133619bb11d17105af8b4901844f2ea0305fe903d09879ee8dc9ac2b66cf28093b012a5e3
    ENCRYPTION_KEY: "A1B2C3D4E5F6G4"
  before_script:
    - sleep 10
  script:
    - echo "Done"
    - sleep 10
  cache:
    - key: vendor_$CI_BRANCH
      paths:
        - vendor/bundle

- name: test:rspec
  stage: test
  image: sujoydatta/ac_docker_image:stable
  environment:
    TWO_FACTOR_KEY: 03238c9f03a392470c1608d0961b7941d455864995f7373ba4bb378133619bb11d17105af8b4901844f2ea0305fe903d09879ee8dc9ac2b66cf28093b012a5e3
    ENCRYPTION_KEY: "A1B2C3D4E5F6G4"
  services:
    - image: mysql:5.7.22
      name: mysql_test
      environment:
        MYSQL_DATABASE: ac_test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: root
  before_script:
    - sleep 10
  script:
    - echo "Done"
    - sleep 10
  only:
    branches:
      - develop_staff_staging
      - develop_staff

- name: deploy:develop_staff_staging
  stage: deploy
  image: sunci/ruby:2.5.1
  before_script:
    - sleep 10
  script:
    - echo "Done"
    - sleep 10
  only:
    branches:
      - develop_staff_staging
  except:
    events:
      - pull_request

- name: deploy:develop_staff
  stage: deploy
  image: sunci/ruby:2.5.1
  before_script:
    - sleep 10
  script:
    - echo "Done"
    - sleep 10
  only:
    branches:
      - develop_staff
  except:
    events:
      - pull_request
