workspace: true

stages:
  - build
  - test

jobs:
  - name: Job1
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - app/Http
      expires_in: 3 days

  - name: Job 2
    stage: test
    image: sunci/capistrano:latest
    script:
      - sleep 5
      
  - name: Job 3
    stage: test
    image: sunci/capistrano:latest
    script:
      - sleep 5
      - echo done
