workspace: true

stages:
  - build
  - test
  - deploy

jobs:
  - name: Job1
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - app/Http
      expires_in: 3 days
    deployment:
      environment: test
      url: https://htt.com
  
  - name: Job33
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - app/Http
      expires_in: 3 days
    deployment:
      environment: test
      url: https://htt.com

  - name: Job 2
    stage: test
    image: node:12-alpine
    script:
      - sleep 5
      
  - name: Job 3
    stage: test
    image: node:12-alpine
    deployment:
      environment: production
      url: https://htt22.com
    script:
      - sleep 5
      - echo done
  - name: Job 4
    stage: deploy
    image: node:12-alpine
    deployment:
      environment: production
      url: https://htt.com
    script:
      - sleep 5
      - echo done
