workspace: false

stages:
  - install
  - build
  - test
  - deploy

jobs:
  - name: Composer Install
    stage: install
    image: sunasteriskrnd/php-workspace:7.4
    script:
    - composer install
  
  - name: Job1
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - app/Http
      expires_in: 3 days
    release:
      environment: test
      url: https://htt.com
  
  - name: Job33
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la
      - echo "Build title should take only subject from commit message"
    after_script:
      - echo "Build title should take only subject from commit message"
    artifacts:
      paths:
      - app/Http
      expires_in: 3 days
    release:
      environment: test
      url: https://htt.com

  - name: Allow failed job
    stage: test
    image: node:12-alpine
    script:
      - sleep 5
      - exit 1
      
  - name: Job 3
    stage: test
    image: node:12-alpine
    release:
      environment: production
      url: https://htt22.com
    script:
      - sleep 5
      - echo done
  - name: Job 4
    stage: deploy
    image: node:12-alpine
    release:
      environment: production
      url: https://htt.com
    script:
      - sleep 5
      - echo done
  - name: Disallow failure
    stage: deploy
    image: node:12-alpine
    release:
      environment: production
      url: https://htt.com
    script:
      - sleep 5
      - exit 0
