stages:
  - build
  - nothing
  - test
  - trigger

jobs:
  build:
    stage: build
    image: node:12-alpine
    workspace: shared
    services:
      - redis:alpine
    before_script:
      - echo before_script
    script:
      - ls -la /
      - ulimit -a
      - sleep 10
      - echo "shared workspace"
  build2:
    stage: build
    image: node:12-alpine
    services:
      - redis:alpine
    script:
      - ls -la /
      - echo "none workspace"

  test:
    stage: test
    image: alpine
    script:
      - sleep 10
      - echo 'except develop'
  test2:
    stage: test
    image: alpine
    script:
      - sleep 10
      - echo "None workspace"
    except:
      branches:
        - master
  test3:
    stage: test
    image: alpine
    script:
      - sleep 10
      - echo 'a'
    except:
      branches:
        - develop
  
  trigger1:
    stage: trigger
    image: alpine
    script:
      - sleep 5
      - echo hihihihihi
    when: manual
