registries:
  registry.gitlab.com:
    username: user_$CI_BUILD_ID
    password: $PASS
  registry2.gitlab.com:
    username: $USER
    password: $PASS

stages:
  - one
  - two
  - three
  - four


workspace: false

jobs:
  - name: One one
    stage: one
    image: alpine
    workspace: shared
    script:
    - echo "Generate coverage file"
    - echo 'xxx' > sharedWorkspace
    coverage:
      type: clover
      path: coverage_php.xml
    artifacts:
      name: aaaa
      expires_in: 3 days
      paths:
      - coverage.xml
  
  - name: One two
    stage: one
    image: alpine
    script:
    - echo "None workspace"
      
  - name: Two one
    stage: two
    image: alpine
    workspace: shared
    environment:
    - APP_ENV=testing
    script:
    - echo "Generate coverage file"
    - cat sharedWorkspace
    - ls -la
    - pwd
    artifacts:
      name: hahaha
      expires_in: 3 days
      paths:
      - coverage.xml
      
  - name: Three one
    stage: three
    image: alpine
    script:
    - echo "Generate cobertura2  file"
    - ls -la
    coverage:
      type: cobertura
      path: cobertura.xml
  
  - name: Four one
    stage: four
    image: sunasteriskrnd/php-workspace:7.4
    environment:
    - APP_ENV=testing1
    script:
    - echo "Generate jacoco  file"
    - ls -la
    - pwd
    coverage:
      type: jacoco
      path: coverage.xml
      
  - name: Four two
    stage: four
    image: alpine
    script:
    - echo "None workspace"    
  
  - name: Four three
    stage: four
    image: alpine
    workspace: shared
    script:
    - echo "shared workspace"  
    - ls -la
