.only-staging: &staging-commits
  branches:
    - develop
  events:
    - push

.only-production: &production-commits
  branches:
    - master
  events:
    - push

.build-and-release-script: &build-and-release
  stage: build
  image: docker:stable
  script:
    - echo "build:production"
    - echo $((RANDOM % 4))
    - exit $(shuf -i 0-1 -n 1)

.deploy-to-server-script: &deploy-to-server
  stage: deploy
  image: thphuong/ssh-client:latest
  script:
    - echo "deploy:production"

#---------------------------------------------------------------------
# MAIN SCRIPT
#---------------------------------------------------------------------

workspace: true

stages:
  - install
  - check
  - build
  - deploy

jobs:
  # Running tests: phpcs, phpunit...
  check:phpcs:
    stage: check
    image: sunasteriskrnd/php-workspace:7.3
    allow_failure: true
    script:
      - watch -n 1 date

  check:build:
    stage: check
    image: node:10-alpine
    script:
      - echo "check:build"

  # Build docker images:

  build:production:
    <<: *build-and-release
    environment:
      TAG: stable
      APP_URL: https://accounts.viblo.asia
      IMAGES_URL: https://images.viblo.asia
      VIBLO_SUBDOMAIN: "null"
      VIBLO_CODE_SUBDOMAIN: code
      VIBLO_CV_SUBDOMAIN: cv
      VIBLO_CTF_SUBDOMAIN: ctf
      VIBLO_MAYFEST_SUBDOMAIN: mayfest

  # Apply new images in server:

  deploy:production:
    <<: *deploy-to-server
    environment:
      TAG: stable
      SERVER: 139.162.17.246
    release:
      environment: production
      url: https://accounts.viblo.asia
