workspace: true

stages:
  - openapi
  - build
  - test

jobs:
  - name: Openapi-validate
    stage: openapi
    image: usabillabv/openapi3-validator
    script:
      - pwd
      - ls -la
      - openapi-validator stawm-server.v1.yaml
    artifacts:
      paths:
        - openapi/docs
      expires_in: 7 days

  - name: Openapi-docs
    stage: openapi
    image: openapitools/openapi-generator-cli
    script:
      - generate -i stawm-server.v1.yaml -g html2 -o openapi/docs/
    artifacts:
      paths:
        - openapi/docs
      expires_in: 7 days

  - name: Build php
    stage: build
    image: sunasteriskrnd/php-workspace:7.4
    services:
      - image: postgres:9.6-alpine
        environment:
          POSTGRES_DB: stawm-testing
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        environment:
          - discovery.type=single-node
          - cluster.name=stawm-docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cache:
      - key: composer_vendor_$CI_BRANCH
        paths:
          - vendor
    before_script:
      - curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer && \
        chmod +x php-cs-fixer && \
        mv php-cs-fixer /usr/bin/php-cs-fixer
      - cp .env.docker .env
      - cp .env.docker.testing .env.testing
      - composer install
      - php artisan cache:clear
    script:
      - php artisan migrate --force
      - php artisan db:seed --force

  - name: Test
    stage: test
    image: sunasteriskrnd/php-workspace:7.4
    workspace: shared
    script:
      - ./vendor/bin/phpunit

  - name: Lint
    stage: test
    image: sunasteriskrnd/php-workspace:7.4
    workspace: shared
    script:
      - php-cs-fixer fix --dry-run --diff --diff-format udiff
