workspace: false

registries:
  registry.gitlab.com:
    username: user_$CI_BUILD_ID
    password: $PASS
  registry2.gitlab.com:
    username: $USER
    password: $PASS

stages:
  - Test
  - build
  - test
  - deploy

jobs:
  - name: CommitLint
    stage: Test
    image: sunci/commitlint:latest
    before_script:
    - echo "module.exports = {extends:\ ['@commitlint/config-conventional']}" > commitlint.config.js
    - cat commitlint.config.js
    script:
    - export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
    - echo "$COMMIT_MESSAGE" | commitlint

  - name: PHPUnit
    stage: Test
    image: sunasteriskrnd/php-workspace:7.4
    registry: registry.gitlab.com
    environment:
    - APP_ENV=testing
    script:
    - echo "Generate coverage file"
    coverage:
      type: clover
      path: coverage.xml
      
  - name: Cobertura
    stage: Test
    image: sunasteriskrnd/php-workspace:7.4
    environment:
    - APP_ENV=testing1
    script:
    - echo "Generate cobertura2  file"
    coverage:
      type: cobertura
      path: cobertura.xml
  
  - name: Demo0
    stage: test
    image: sunasteriskrnd/php-workspace:7.4
    environment:
    - APP_ENV=testing
    script:
    - echo "Generate coverage file"
    artifacts:
      name: hahaha
      expires_in: 3 days
      paths:
      - coverage.xml
