workspace: false

stages:
  - Test
  - build
  - test
  - deploy

jobs:
  - name: PHPUnit
    stage: Test
    image: sunasteriskrnd/php-workspace:7.4
    environment:
    - APP_ENV=testing
    script:
    - echo "Generate coverage file"
    coverage:
      type: clover
      path: coverage.xml
