dist: trusty
language: php

php:
  - 7.1

services:
  - mysql

before_script:
script:
  - echo 1
addons:
  artifacts:
    # ⋮
    working_dir: out
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - vendor
env:
  - TRAVIS_NODE_VERSION="8"
