version: 2
jobs:
  shellcheck:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: cat unformat_str.txt 
workflows:
  version: 2
  check-build:
    jobs:
      - shellcheck
      
